version: "2"
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    volumes:
      - ./app/mongod.conf:/etc/mongod.conf
    ports:
      - "27017:27017"
    # command: node ./app/seeds/seed.js

  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - mongo
    environment:
      - DB_HOST=mongodb://mongo:27017/posts
    command: bash -c "node /app/seeds/seed.js && cd /app && node app.js"
